data_path: data/cellphones/
dataset: Amazon_Cellphones_01_01
checkpoint_dir: data/cellphones/Amazon_Cellphones_01_01/saved/
results_dir: results/frej/Amazon_Cellphones_01_01/
benchmark_filename: ['train', 'validation', 'test']

gpu_id: -1

model: Pop

run_num: 1

eval_args:
    mode: full
metrics: ['MRR', 'NDCG', 'Hit', 'Precision', 'Recall']
topk: [1, 3, 5, 10, 20]
valid_metric: Hit@10
metric_decimal_place: 4

log_wandb: False
wandb_project: recbole

seed: 4